### ISSUE TITLE
Some statistics files could be missing?

### ISSUE THREAD

**Issue by claudeyj** [microsoft/codamosa-dataset#1]
Hi, I tried to analyze the statistics files with scripts, but it seems that some unziped directories don't contain statistics files (and two test_*.py files). Am I missing something? Or Codamosa just cannot evolutionarily search over some codex-generated tests? Thanks for your time in advance.

**Comment by carolemieux** [comment]
There are certain runs on which CodaMOSA (and also some on which MOSA) did not terminate correctly for some reason. I don't know the exact reason why this happened, as there are so many benchmarks, I was not able to analyze them all. 

The statistics and test files only are generated at the end of the run, during the Pynguin termination procedure. The plots in the paper show benchmarks on which >=10 runs successfully terminated.
