### ISSUE TITLE
Broken zipped csv file

### ISSUE THREAD

**Issue by claudeyj** [microsoft/codamosa-dataset#2]
Hi,
I'm trying to extract statistics files and it looks like there's one broken csv file. Steps to reproduce:
```
cd final-exp
unzip cookiecutter.zipfile.zip -d tmp_unzip
cd tmp_unzip/codamosa-0.8
cd cookiecutter.zipfile-9
cat statistics.csv
```
Then you can observe that something is missing at the end of this file.

**Comment by carolemieux** [comment]
I just checked, and the file is broken in the original data as well, so I cannot provide a fix. Probably for a similar reason as described in Issue #1, that there are some runs which could not terminate properly. Such runs were excluded from the analysis in Fig 3. 

I will note that the codamosa-0.8 config is not the configuration of CodaMOSA used throughout the paper, it is CodaMOSA-No-UnInterp. While the main configuration of CodaMOSA is codamosa-0.8-uninterp.
